import { createElement } from 'lwc';
import PT_aprobacionProductos from 'c/pT_aprobacionProductos';

describe('c-p-t-aprobacion-productos', () => {
    afterEach(() => {
        // The jsdom instance is shared across test cases in a single file so reset the DOM
        while (document.body.firstChild) {
            document.body.removeChild(document.body.firstChild);
        }
    });

    it('TODO: test case generated by CLI command, please fill in test logic', () => {
        // Arrange
        const element = createElement('c-p-t-aprobacion-productos', {
            is: PT_aprobacionProductos
        });

        // Act
        document.body.appendChild(element);

        // Assert
        // const div = element.shadowRoot.querySelector('div');
        expect(1).toBe(1);
    });
});